// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6vRmBwios3vufVZ8N-UPIRNa7ZfqStg',
    appId: '1:593063368438:web:c3fa84efbf051cc9387ed7',
    messagingSenderId: '593063368438',
    projectId: 'wavelngth-oauth',
    authDomain: 'wavelngth-oauth.firebaseapp.com',
    storageBucket: 'wavelngth-oauth.appspot.com',
    measurementId: 'G-R2F0F774VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsySlIxH94q4Vsy4sof01n_7a9X01Pngw',
    appId: '1:593063368438:android:3d9b4198d2fca764387ed7',
    messagingSenderId: '593063368438',
    projectId: 'wavelngth-oauth',
    storageBucket: 'wavelngth-oauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCCSQYH85q_96I88lx5-JhbjoAQStq3A',
    appId: '1:593063368438:ios:34c9059b9cbe8ac9387ed7',
    messagingSenderId: '593063368438',
    projectId: 'wavelngth-oauth',
    storageBucket: 'wavelngth-oauth.appspot.com',
    androidClientId: '593063368438-p2ld2pgdbpbj99htk9h8bcdd3qeea593.apps.googleusercontent.com',
    iosClientId: '593063368438-u20df0dc6v9u1i00m6abm81agrrs8ut9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdCCSQYH85q_96I88lx5-JhbjoAQStq3A',
    appId: '1:593063368438:ios:34c9059b9cbe8ac9387ed7',
    messagingSenderId: '593063368438',
    projectId: 'wavelngth-oauth',
    storageBucket: 'wavelngth-oauth.appspot.com',
    androidClientId: '593063368438-p2ld2pgdbpbj99htk9h8bcdd3qeea593.apps.googleusercontent.com',
    iosClientId: '593063368438-u20df0dc6v9u1i00m6abm81agrrs8ut9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe6vRmBwios3vufVZ8N-UPIRNa7ZfqStg',
    appId: '1:593063368438:web:5f10540a2c5f50e7387ed7',
    messagingSenderId: '593063368438',
    projectId: 'wavelngth-oauth',
    authDomain: 'wavelngth-oauth.firebaseapp.com',
    storageBucket: 'wavelngth-oauth.appspot.com',
    measurementId: 'G-D3FQXEMNJE',
  );
}
